### ISSUE TITLE
Unknown problem with BIOMOD_Projection

### ISSUE THREAD

**Issue by LorenzoBernicchi** [biomodhub/biomod2#168]
Hello everyone,
when running my species distribution models, everything was going great until starting the BIOMOD_Projection part.

When projecting a single model, these messages on the screen started to appear, each once for every model:

**proj_create_from_database: datum not found
proj_create_from_database: ellipsoid not found
proj_create_from_database: prime meridian not found**

R didn't stop working, s I let it finish and it completed the operation without any error message.
At that point I started BIOMOD_EnsembleForecasting and, after a few minutes of operation in which the above messages kept appearing continuously on the screen, I got this error:

**Error in .fun_testIfIn(TRUE, "full.name", subset.list[["full.name"]],  :
full.name must be 'lyr1', 'lyr1', 'lyr1', 'X1', './Capreolus.capreolus/models/CAPRIOLO/Capreolus.capreolus_PA1_RUN1_MAXENT_outputs/projMaxent.asc', 'lyr1', 'lyr1', 'lyr1', 'lyr1', 'X1', './Capreolus.capreolus/models/CAPRIOLO/Capreolus.capreolus_PA1_RUN2_MAXENT_outputs/projMaxent.asc', 'lyr1', 'lyr1', 'lyr1', 'lyr1', 'X1', './Capreolus.capreolus/models/CAPRIOLO/Capreolus.capreolus_PA1_RUN3_MAXENT_outputs/projMaxent.asc', 'lyr1', 'lyr1', 'lyr1', 'lyr1', 'X1', './Capreolus.capreolus/models/CAPRIOLO/Capreolus.capreolus_PA1_RUN4_MAXENT_outputs/projMaxent.asc', 'lyr1', 'lyr1', 'lyr1', 'lyr1', 'X1', './Capreolus.capreolus/models/CAPRIOLO/Capreolus.capreolus_PA1_RUN5_MAXENT_outputs/projMaxent.asc', 'lyr1', 'lyr1', 'lyr1', 'lyr1', 'X1', './Capreolus.capreolus/models/CAPRIOLO/Capreolus.capreolus_PA1_RUN6_MAXENT_outputs/projMaxent.asc', 'lyr1', 'lyr1', 'lyr1', 'lyr1', 'X1', './Capreolus.capreolus/models/CAPRIOLO/Capreolus.capreolus_PA1_RUN7_MAXENT_outputs/projMaxent.asc', 'lyr1', 'lyr1'**

What could be the source of the error? To read the presence data and variables I am using the terra package and have reprojected everything in EPSG 3035. When I used the FormatingData function I did not receive any errors.

**Comment by rpatin** [comment]
Hello Lorenzo,
Thank you for reporting :pray: 
Could you give a bit more information on your workflow:
- Can you share the code you used to call `BIOMOD_FormatingData` ; `BIOMOD_Modeling` ; `BIOMOD_Projection` ; ``BIOMOD_EnsembleModeling` ; `BIOMOD_EnsembleForecasting` ?
- Did you run only `MAXENT` models ?
- What does the output of your `BIOMOD_Projection` look like ? `show(myBiomodProj)` ; `show(get_predictions(myBiomodProj))`

I can imagine that there is an issue with Maxent, which uses ASCII raster which may not handle the projection very well (although it is just a guess).

Cheers,
Rémi

**Comment by LorenzoBernicchi** [comment]
Hello Rémi,
first of all thank for answer me!

Hereafter you can find the codes I used for the biomod functions:

```
Roedeer_data` <- BIOMOD_FormatingData(resp.name = "Capreolus capreolus",
                                    resp.var = Roedeer_points,
                                    expl.var = Variables,
                                    PA.nb.rep = 1,
                                    PA.nb.absences = 10000,
                                    PA.strategy = 'random')
```

```
Roedeer_models <- BIOMOD_Modeling(bm.format = Roedeer_data,
                                 modeling.id = "CAPRIOLO",
                                 models = c("GLM", "GBM", "GAM", "RF",
                                            "MAXENT", "MAXNET"),
                                 bm.options = myBiomodOption,
                                 nb.rep = 10,
                                 data.split.perc = 70,
                                 metric.eval = c("TSS", "ROC"),
                                 var.import = 3,
                                 save.output = T,
                                 do.full.models = F,
                                 do.progress = T)
```

```
Roedeer_ensemble_models <- BIOMOD_EnsembleModeling(bm.mod = Roedeer_models,
                                                  models.chosen = "all",
                                                  em.by = "all",
                                                  metric.select = c("ROC"),
                                                  metric.select.thresh = c(0.7),
                                                  metric.eval = c("TSS", "ROC"),
                                                  prob.mean = FALSE,
                                                  prob.cv = FALSE,
                                                  prob.ci = FALSE,
                                                  prob.median = FALSE,
                                                  committee.averaging = TRUE,
                                                  prob.mean.weight = TRUE,
                                                  var.import = 3)
```

```
Roedeer_proj <- BIOMOD_Projection(bm.mod = Roedeer_models,
                                 new.env = Variables,
                                 proj.name = "Roedeer_single",
                                 models.chosen = "all",
                                 metric.binary = NULL,
                                 do.stack = TRUE,
                                 on_0_1000 = TRUE,
                                 build.clamping.mask = FALSE,
                                 output.format = '.grd')
```

```
Roedeer_ensemble_proj <- BIOMOD_EnsembleForecasting(
  bm.em = Roedeer_ensemble_models,
  bm.proj = Roedeer_proj,
  proj.name = "Roedeer_ensemble",
  models.chosen = "all",
  metric.binary =  NULL,
  on_0_1000 = TRUE,
  do.stack = TRUE,
  build.clamping.mask = FALSE,
  output.format = '.grd')
```

As you can see, I didn't use only maxent models

I also had an additional question.. Today I am trying to modeling another species, and when it comes to modeling MAXNET sometimes I get this error: **Error in { : task 5 failed - "cannot open the connection"
In addition: Warning message:
In file(con, "r") :
  cannot open file './Vulpes.vulpes/models/VOLPE/Vulpes.vulpes_PA1_RUN3_MAXENT_outputs/maxent.stderr': Permission denied**

I already saw an issue where the problem was the same, but I still don't figure out why this happens.
I think the problem could be MAXNET, since both errors I am showing come when biomod starts this algorithm.

**Comment by LorenzoBernicchi** [comment]
Hello @rpatin 
sorry but I forgot to add this part.

This Is what I get running ``show(myBiomodProjection)``:

```

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.projection.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Projection directory : ./Meles.meles/Badger_single


sp.name : Meles.meles

expl.var.names : Coniferous_Forests Deciduous_Forests Global_Model Pastures Settlements 
Shrublands TRI aspect DEM


modeling.id : TASSO ( ./Meles.meles/Meles.meles.TASSO.models.out )

models.projected : 
Meles.meles_PA1_RUN1_GLM, Meles.meles_PA1_RUN1_GBM, Meles.meles_PA1_RUN1_GAM, Meles.meles_PA1_RUN1_RF, Meles.meles_PA1_RUN1_MAXNET, Meles.meles_PA1_RUN2_GLM, Meles.meles_PA1_RUN2_GBM, Meles.meles_PA1_RUN2_GAM, Meles.meles_PA1_RUN2_RF, Meles.meles_PA1_RUN2_MAXNET, Meles.meles_PA1_RUN3_GLM, Meles.meles_PA1_RUN3_GBM, Meles.meles_PA1_RUN3_GAM, Meles.meles_PA1_RUN3_RF, Meles.meles_PA1_RUN3_MAXNET, Meles.meles_PA1_RUN4_GLM, Meles.meles_PA1_RUN4_GBM, Meles.meles_PA1_RUN4_GAM, Meles.meles_PA1_RUN4_RF, Meles.meles_PA1_RUN4_MAXNET, Meles.meles_PA1_RUN5_GLM, Meles.meles_PA1_RUN5_GBM, Meles.meles_PA1_RUN5_GAM, Meles.meles_PA1_RUN5_RF, Meles.meles_PA1_RUN5_MAXNET, Meles.meles_PA1_RUN6_GLM, Meles.meles_PA1_RUN6_GBM, Meles.meles_PA1_RUN6_GAM, Meles.meles_PA1_RUN6_RF, Meles.meles_PA1_RUN6_MAXNET, Meles.meles_PA1_RUN7_GLM, Meles.meles_PA1_RUN7_GBM, Meles.meles_PA1_RUN7_GAM, Meles.meles_PA1_RUN7_RF, Meles.meles_PA1_RUN7_MAXNET, Meles.meles_PA1_RUN8_GLM, Meles.meles_PA1_RUN8_GBM, Meles.meles_PA1_RUN8_GAM, Meles.meles_PA1_RUN8_RF, Meles.meles_PA1_RUN8_MAXNET, Meles.meles_PA1_RUN9_GLM, Meles.meles_PA1_RUN9_GBM, Meles.meles_PA1_RUN9_GAM, Meles.meles_PA1_RUN9_RF, Meles.meles_PA1_RUN9_MAXNET, Meles.meles_PA1_RUN10_GLM, Meles.meles_PA1_RUN10_GBM, Meles.meles_PA1_RUN10_GAM, Meles.meles_PA1_RUN10_RF, Meles.meles_PA1_RUN10_MAXNET

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```
Everything seems okay, I think there is nothing strange in it. 

On the other hand, using ```show(get_predictions(Badger_proj))```, after a bunch of these messages **(proj_create_from_database: datum not found
proj_create_from_database: ellipsoid not found
proj_create_from_database: prime meridian not found)** I get this:
```
class       : SpatRaster 
dimensions  : 1307, 1307, 50  (nrow, ncol, nlyr)
resolution  : 100, 100  (x, y)
extent      : 4496516, 4627216, 2494261, 2624961  (xmin, xmax, ymin, ymax)
coord. ref. : ETRS89-extended / LAEA Europe (EPSG:3035) 
sources     : spat_QCW28eR8kc864ye_2332.tif  
              spat_IpxzGGgBLQVJ4fc_2332.tif  
              spat_bTaKWh8nRTpYXOr_2332.tif  
              ... and 47 more source(s)
names       : lyr1, lyr1, lyr1,  X1, lyr1, lyr1, ... 
min values  :   41,   42,    0,   0,    0,  355, ... 
max values  :  806,  866, 1000, 592,  954,  833, ... 
```

**Comment by rpatin** [comment]
Hello Lorenze,
Thank you for all the additional information :pray: 

1. Finally the problem was not linked neither to `MAXENT` nor to projection issue, but rather to the fact that you used a large number of raster that could not be loaded in memory and for which `biomod2` uses temporary raster files on the disk (e.g. spat_QCW28eR8kc864ye_2332.tif`). Unfortunately this option broke the naming of the raster layer in the internal management (as you can see with names such as `lyr1` although it should be a model name).
This is now fixed on github so if you install the up-to-date version (`4.2-3` with `install_github('biomodhub/biomod2')`)

2. Concerning the projection warnings such as  `proj_create_from_database: datum not found` : to my opinion they are not an issue. It should just be the result of our - not always rigorous - internal management of raster and projection (but no reprojection are ever used within the package).

3. Concerning the MAXENT error, I would need a bit more explanation on the issue:
- are you doing something differently for Vulpes vulpes compared to other species ?
- If not I would probably need your data to be able to understand what is happening. Maxent error are quite tricky to debug ... (here is my mail: remi.patin@univ-grenoble-alpes.fr)
- I would also appreciate if you could open a new issue for the MAXENT error, this would be clearer for everyone :wink: 

Of course, feel free to let us know if the `EnsembleForecasting` issue persist.
Cheers,
Rémi

**Comment by LorenzoBernicchi** [comment]
Dear @rpatin ,
1. Actually, I tried to use the latest version of biomod (4.2-3) but the problem still remains. I tried every version till the 3.5.1 and this is the only one that do not give me any problems. Up to now  discarded MAXENT and everything is going great! :)
2.  Thanks for that, I already made some research on the terra package and that is not a problem!
3. Regarding the MAXENT error, I updated both Java and Maxent versions on my PC and the problem doesn't occur anymore! 

Thanks for everything, I wish you a good day!
