### ISSUE TITLE
RF sample sizes in default modeling options

### ISSUE THREAD

**Issue by jllancaster** [biomodhub/biomod2#267]
Hi there,

I am trying to understand what the sample size might be for the RF method and hoping I could get some help. My goal is to incorporate a down-sampling technique with RF to optimize for a large number of background points relative to presences (10,000 background and 650 presences) following the recommendations in Valavi et al. 2022 (https://doi.org/10.1002/ecm.1486). Effectively in what Valavi et al. term as RF down-sampled, each sample should have an equal number of presence as background points.

What does the 'NULL' argument in sampsize for RF mean? I can't figure it out from the randomForest docs. Note that I've changed the default `ntree` here to 1000.

```
RF = list( do.classif = TRUE,
           ntree = 1000,
           mtry = 'default',
           sampsize = NULL,
           nodesize = 5,
           maxnodes = NULL),
```

**Comment by rpatin** [comment]
Hi @jllancaster,
Thank you for reporting :pray:

From the doc of `randomForest::randomForest`:

> **sampsize** 
> Size(s) of sample to draw. For classification, if sampsize is a vector of the length the number of strata, then sampling is  stratified by strata, and the elements of sampsize indicate the numbers to be drawn from the strata.

And from issue https://github.com/biomodhub/biomod2/issues/172#issuecomment-1415995700:
> I think the correct way would be to provide `sampsize = c(700,700)` if you want `randomForest` to sample 700 absences and 700 presences (i.e. all of the presences once accounting for cross-validation)
> 
> If you want e.g. 1000 absences and 700 presences you would need to provide `sampsize = c(1000,700)`

Best regards,
Rémi

**Comment by jllancaster** [comment]
Hi @rpatin, thank you very much, much easier than I thought it would be. I was clearly overthinking this, and apologies for missing issue #172.

**Comment by jllancaster** [comment]
Hi @rpatin, after changing the sample size settings like this, RF models are not being produced by BIOMOD_Modeling. Note that I've tested this using `do.classif = TRUE` and `do.classif = FALSE`. Any idea what might be going on? Pasted some example code of what I'm doing below. Can post a MWE if needed. Thanks!

`# set up parallel computing ----
library(doParallel)
library(parallelly)
nbcores <- availableCores(omit = 2)
registerDoParallel(nbcores)

# Build model dataset from raster stack and occ data ----
ARCAL_data <- BIOMOD_FormatingData(resp.var = thin_occ['ARCAL'],
                                   resp.xy = thin_occ[, c('long', 'lat')],
                                   expl.var = covars_nocor,
                                   resp.name = "ARCAL",
                                   PA.nb.rep = 10,
                                   PA.nb.absences = 10000,
                                   PA.strategy = 'random')

# set modeling options for RF downsampled ----
ARCAL_opt@RF$do.classif <- FALSE

ARCAL_opt <- BIOMOD_ModelingOptions(
    RF = list( do.classif = FALSE,
      ntree = 1000,
      mtry = 'default',
      sampsize = c(642, 642),
      nodesize = 5,
      maxnodes = NULL))

ARCAL_models

## Run Single Models ----
ARCAL_models <-
  BIOMOD_Modeling(
    ARCAL_data,
    modeling.id = as.character(format(Sys.time(), "%s")),
    models = c("MAXNET", "GBM", "RF"),
    bm.options = ARCAL_opt,
    CV.strategy = "random",
    CV.nb.rep = 5,
    CV.perc = 0.70,
    metric.eval = c("ROC", "TSS"),
    nb.cpu = 1,
    var.import = 3,
    seed.val = 702
  )`

**Comment by rpatin** [comment]
Hi @jllancaster,
We are investigating the issue.
do you get the following error ?

```
-=-=-=--=-=-=- GuloGulo_allData_allRun_RF 

Model=Breiman and Cutler's random forests for classification and regression
	> RF modeling...Error in randomForest.default(m, y, ...) : 
  sampsize can not be larger than class frequency
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'predict': object 'model.bm' not found
```

Best,
Rémi

**Comment by rpatin** [comment]
Hi @jllancaster,
I think I got the problem, we were not formatting properly argument `strata` of `randomForest`. It should be fixed now if you update to current github version with `devtools::install_github('biomodhub/biomod2')`
Best,
Rémi

**Comment by jllancaster** [comment]
Good lord @rpatin thank you for the quick response! I’ve updated and gone through the model runs again. I’m trying to parallelize this, and I did not receive the error you posted. Looks like I’m still seeing the same behavior. I’m going to try a run without a parallel backend and see if that changes anything.

**Comment by jllancaster** [comment]
@rpatin yeah here is the error thrown when I turn off parallel:

Model=Breiman and Cutler's random forests for classification and regression
	> RF modeling...Error in randomForest.default(m, y, ...) : 
  sampsize should be of length one
In addition: Warning messages:
1: executing %dopar% sequentially: no parallel backend registered 
2: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'predict': object 'model.bm' not found

**Comment by rpatin** [comment]
Concerning the error with the regression, according to the doc, sampling by strata (i.e. `sampsize` of length >1)  is not compatible with the regression RF (i.e. `do.classif = FALSE`). 

Concerning the error when `do.classif = TRUE`, perhaps it is linked to your `randomForest` version ? Can you send the output of `sessionInfo()` ?

**Comment by jllancaster** [comment]
Okay got it with the regression, thank you:

Here is the session info:

> sessionInfo()
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gbm_2.1.8.1     biomod2_4.2-3-4

loaded via a namespace (and not attached):
 [1] pkgload_1.3.2          splines_4.2.3          foreach_1.5.2         
 [4] Formula_1.2-5          shiny_1.7.4            sp_1.6-1              
 [7] remotes_2.4.2          sessioninfo_1.2.2      pillar_1.9.0          
[10] lattice_0.20-45        glue_1.6.2             pROC_1.18.2           
[13] digest_0.6.31          promises_1.2.0.1       randomForest_4.7-1.1  
[16] colorspace_2.1-0       htmltools_0.5.5        httpuv_1.6.9          
[19] Matrix_1.5-4           plyr_1.8.8             pkgconfig_2.0.3       
[22] devtools_2.4.5         maxnet_0.1.4           PresenceAbsence_1.1.11
[25] earth_5.3.2            purrr_1.0.1            xtable_1.8-4          
[28] scales_1.2.1           processx_3.8.0         terra_1.7-29          
[31] later_1.3.0            TeachingDemos_2.12     tibble_3.2.1          
[34] mgcv_1.8-42            mda_0.5-3              generics_0.1.3        
[37] ggplot2_3.4.2          usethis_2.1.6          ellipsis_0.3.2        
[40] withr_2.5.0            cachem_1.0.7           nnet_7.3-18           
[43] cli_3.6.1              survival_3.5-3         magrittr_2.0.3        
[46] crayon_1.5.2           mime_0.12              memoise_2.0.1         
[49] ps_1.7.4               fs_1.6.1               fansi_1.0.4           
[52] nlme_3.1-162           doParallel_1.0.17      MASS_7.3-58.3         
[55] class_7.3-21           pkgbuild_1.4.0         profvis_0.3.7         
[58] tools_4.2.3            prettyunits_1.1.1      lifecycle_1.0.3       
[61] stringr_1.5.0          glmnet_4.1-7           munsell_0.5.0         
[64] plotrix_3.8-2          callr_3.7.3            compiler_4.2.3        
[67] rlang_1.1.1            plotmo_3.6.2           grid_4.2.3            
[70] iterators_1.0.14       rstudioapi_0.14        htmlwidgets_1.6.2     
[73] miniUI_0.1.1.1         gtable_0.3.3           codetools_0.2-19      
[76] abind_1.4-5            reshape_0.8.9          reshape2_1.4.4        
[79] R6_2.5.1               dplyr_1.1.2            fastmap_1.1.1         
[82] utf8_1.2.3             shape_1.4.6            stringi_1.7.12        
[85] parallel_4.2.3         Rcpp_1.0.10            vctrs_0.6.2           
[88] rpart_4.1.19           tidyselect_1.2.0       urlchecker_1.0.1

**Comment by rpatin** [comment]
Indeed you have the same version as I do so it should not be linked to that ...
Could you show a summary of your data and modeling options ?
```
show(ARCAL_data)
show(ARCAL_opt)
```

**Comment by rpatin** [comment]
Indeed you have the same version as I do so it should not be linked to that ...
Could you show a summary of your data and modeling options ?
```
show(ARCAL_data)
show(ARCAL_opt)
```

**Comment by jllancaster** [comment]
Sure thing!

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  ARCAL

	 642 presences,  0 true absences and  93969 undefined points in dataset


	 17 explanatory variables

      amp               maxn         northness           eastness       
 Min.   :  0.000   Min.   :100.0   Min.   :-1.00000   Min.   :-1.00000  
 1st Qu.:  6.000   1st Qu.:120.0   1st Qu.:-0.64481   1st Qu.:-0.80641  
 Median :  9.000   Median :127.0   Median :-0.06652   Median :-0.04570  
 Mean   :  9.749   Mean   :126.6   Mean   :-0.03066   Mean   :-0.02254  
 3rd Qu.: 13.000   3rd Qu.:134.0   3rd Qu.: 0.58549   3rd Qu.: 0.76591  
 Max.   :255.000   Max.   :255.0   Max.   : 1.00000   Max.   : 1.00000  
     cvtmax         avewinppt         cvwinppt         exttmin           dur       
 Min.   :0.9250   Min.   : 9.047   Min.   : 8.211   Min.   :261.4   Min.   : 91.0  
 1st Qu.:0.9377   1st Qu.:18.352   1st Qu.:26.096   1st Qu.:272.2   1st Qu.:193.0  
 Median :0.9448   Median :22.630   Median :31.066   Median :274.5   Median :220.0  
 Mean   :0.9458   Mean   :24.575   Mean   :30.536   Mean   :274.1   Mean   :223.5  
 3rd Qu.:0.9536   3rd Qu.:29.733   3rd Qu.:35.982   3rd Qu.:276.2   3rd Qu.:253.0  
 Max.   :0.9958   Max.   :88.003   Max.   :56.674   Max.   :279.8   Max.   :365.0  
      sost             caco3           gypsum        depthbedrock  percentclay   
 Min.   :-150.00   Min.   : 0.00   Min.   : 0.000   Min.   :  0   Min.   : 0.00  
 1st Qu.: -31.00   1st Qu.: 2.00   1st Qu.: 0.000   1st Qu.: 38   1st Qu.:10.30  
 Median :   2.00   Median : 7.00   Median : 0.000   Median :201   Median :12.50  
 Mean   :  29.36   Mean   :10.02   Mean   : 1.092   Mean   :139   Mean   :14.03  
 3rd Qu.:  72.00   3rd Qu.:15.00   3rd Qu.: 0.000   3rd Qu.:201   3rd Qu.:16.80  
 Max.   : 351.00   Max.   :57.00   Max.   :66.000   Max.   :201   Max.   :50.00  
  percentsand     percentsilt     slopepercent    
 Min.   : 0.00   Min.   : 0.00   Min.   :  0.000  
 1st Qu.:45.70   1st Qu.:19.60   1st Qu.:  2.550  
 Median :59.70   Median :23.80   Median :  5.099  
 Mean   :54.15   Mean   :25.46   Mean   :  9.161  
 3rd Qu.:66.80   3rd Qu.:33.60   3rd Qu.: 11.604  
 Max.   :97.90   Max.   :72.30   Max.   :129.262  


 10 Pseudo Absences dataset available ( 
PA1, PA2, PA3, PA4, PA5, PA6, PA7, PA8, PA9, PA10 ) with  
9831 (PA1), 9807 (PA2, PA4), 9813 (PA3), 9827 (PA5), 9825 (PA6), 9819 (PA7), 9809 (PA8), 9805 (PA9), 9814 (PA10) 
pseudo absences

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> show(ARCAL_opt)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.options -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


GLM = list( type = 'quadratic',
            interaction.level = 0,
            myFormula = NULL,
            test = 'AIC',
            family = binomial(link = 'logit'),
            mustart = 0.5,
            control = glm.control(epsilon = 1e-08, maxit = 50, trace = FALSE) ),


GBM = list( distribution = 'bernoulli',
            n.trees = 2500,
            interaction.depth = 7,
            n.minobsinnode = 5,
            shrinkage = 0.001,
            bag.fraction = 0.5,
            train.fraction = 1,
            cv.folds = 3,
            keep.data = FALSE,
            verbose = FALSE,
            perf.method = 'cv',
            n.cores = 1),

GAM = list( algo = 'GAM_mgcv',
            type = 's_smoother',
            k = -1,
            interaction.level = 0,
            myFormula = NULL,
            family = binomial(link = 'logit'),
            method = 'GCV.Cp', 
            optimizer = c('outer','newton'),
            select = FALSE,
            knots = NULL,
            paraPen = NULL,
            control = list(nthreads = 1, ncv.threads = 1, irls.reg = 0
, epsilon = 1e-07, maxit = 200, trace = FALSE, mgcv.tol = 1e-07, mgcv.half = 15
, rank.tol = 1.49011611938477e-08
, nlm = list(ndigit=7, gradtol=1e-06, stepmax=2, steptol=1e-04, iterlim=200, check.analyticals=0)
, optim = list(factr=1e+07)
, newton = list(conv.tol=1e-06, maxNstep=5, maxSstep=2, maxHalf=30, use.svd=0)
, outerPIsteps = 0, idLinksBases = TRUE, scalePenalty = TRUE, efs.lspmax = 15
, efs.tol = 0.1, keepData = FALSE, scale.est = fletcher, edge.correct = FALSE) ),


CTA = list( method = 'class',
            parms = 'default',
            cost = NULL,
            control = list(xval = 5, minbucket = 5, minsplit = 5, cp = 0.001
, maxdepth = 25) ),


ANN = list( NbCV = 5,
            size = NULL,
            decay = NULL,
            rang = 0.1,
            maxit = 200),

SRE = list( quant = 0.025),

FDA = list( method = 'mars',
            add_args = NULL),

MARS = list( type = 'simple',
             interaction.level = 0,
             myFormula = NULL,
             nk = NULL,
             penalty = 2,
             thresh = 0.001,
             nprune = NULL,
             pmethod = 'backward'),

RF = list( do.classif = TRUE,
           ntree = 1000,
           mtry = 'default',
           sampsize = 642 642,
           nodesize = 5,
           maxnodes = NULL),

MAXENT = list( path_to_maxent.jar = 'C:/Users/jdlanc/Documents/RWorking/BearpoppySDM/workdir', 
               memory_allocated = 512,
               initial heap size = NULL,
               maximum heap size = NULL,
               background_data_dir = 'default',
               maximumbackground = 'default',
               maximumiterations = 200,
               visible = FALSE,
               linear = TRUE,
               quadratic = TRUE,
               product = TRUE,
               threshold = TRUE,
               hinge = TRUE,
               lq2lqptthreshold = 80,
               l2lqthreshold = 10,
               hingethreshold = 15,
               beta_threshold = -1,
               beta_categorical = -1,
               beta_lqp = -1,
               beta_hinge = -1,
               betamultiplier = 1,
               defaultprevalence = 0.5),

 MAXNET = list( myFormula = NULL,
     regmult = 1,
     regfun = <function> )
)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by rpatin** [comment]
Thanks for your reactivity :pray: 
I may have one last idea to try before asking for the data.
You are using `sampsize = c(642,642)` although you have only `642` presences and you are asking for cross-validation with `CV.perc = 0.7`. Meaning that your RF function will never see more than ~449 presences. Can you try with` sampsize = c(400,400)` to ensure this is not something like this ?
Best,
Rémi

**Comment by jllancaster** [comment]
Yep, same error as before, sampsize has too many elements. What's the best way to get some data to you?

Also, possibly related/unrelated, I wonder if I am completely overdoing it with the numbers of background points?

`642 presences,  0 true absences and  93969 undefined points in dataset`

When you read in the lit, "we used 50,000 background points"...am I exceeding that figure by some 43k points? I had been shooting for the 10,000 points standard, but calculating 10,000 per PA dataset. I wonder if instead I should be doing something like suggested in the biomod docs, of 3x the number of presences per PA dataset, so n=1926 background points per dataset, for a total of 19,260 background points for a total of 10 PA datasets...

**Comment by rpatin** [comment]
That's quite mysterious :thinking: 
You can send them by mail (remi.patin@univ-grenoble-alpes.fr) or through my university cloud (https://nextcloud.osug.fr/index.php/s/Wk4HybpZ7b4yRTM - a upload-only folder that only I can access)

Concerning the PA I'll answer tomorrow.

**Comment by jllancaster** [comment]
Just taking a look with my data, seeing the expected patterns from the Barbet-Massin et al. 2012 paper:

![image](https://github.com/biomodhub/biomod2/assets/19980931/2b58c8c0-8075-43e2-a366-8c082b354297)

**Comment by rpatin** [comment]
Hi @jllancaster,
I found the problem, in my fix, assumed that all species were named `GuloGulo` :innocent: 
I just pushed the commit to github, so if you update (again) it should now work :crossed_fingers: 
Best,
Rémi

**Comment by rpatin** [comment]
Hi again,
Short answer concerning the pseudo-absences question. I think you should also think the number as relative to your coverage of environmental space. If 3x the presence is enough to have a satisfying coverage of environmental space, it can be overkill to add too much. In opposition 3x the presence may not be enough and you can then be happy to select a higher number.
As you pointed out the influence of PA numbers on model performance can vary with the algorithm. Good thing is that `biomod2` now allows to have different PA dataset and numbers for different algorithm:

> From `biomod2` website:
```
# Select multiple sets of pseudo-absences

# Transform true absences into potential pseudo-absences
myResp.PA <- ifelse(myResp == 1, 1, NA)

# Format Data with pseudo-absences : random method
myBiomodData.multi <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                           expl.var = myExpl,
                                           resp.xy = myRespXY,
                                           resp.name = myRespName,
                                           PA.nb.rep = 4,
                                           PA.nb.absences = c(1000, 500, 500, 200),
                                           PA.strategy = 'random')
myBiomodData.multi
summary(myBiomodData.multi)
plot(myBiomodData.multi)
```

Then you can use argument `models.pa` within `BIOMOD_Modeling` to attribute PA dataset to specific models. For instance:
`models.pa = list("GLM" = c("PA1","PA2"), "MAXENT" = c("PA3") )`

> Also, possibly related/unrelated, I wonder if I am completely overdoing it with the numbers of background points?
> 
> `642 presences, 0 true absences and 93969 undefined points in dataset`
> 
> When you read in the lit, "we used 50,000 background points"...am I exceeding that figure by some 43k points? I had been shooting for the 10,000 points standard, but calculating 10,000 per PA dataset. I wonder if instead I should be doing something like suggested in the biomod docs, of 3x the number of presences per PA dataset, so n=1926 background points per dataset, for a total of 19,260 background points for a total of 10 PA datasets...

**Comment by jllancaster** [comment]
@rpatin thank you so much I am working on running it now with the updated version.

regarding PA datasets of different sizes, currently PA.nb.rep = 10 and I am thoroughly confused on how to maintain that if I use datasets of different sizes...do I need to produce 30 PA datasets, 10 for each model? Apologies if this is dumb...

**Comment by rpatin** [comment]
Yes it would indeed be 30 PA datasets, 10 for each models. You may have to check the numbering but I think it would be 
`PA1 -> PA10` for the first model, `PA11 -> PA20` for the second, etc ...
But if you keep `PA.nb.rep = 10` with 3 different PA number this should automatically produce 30 PA dataset.

**Comment by jllancaster** [comment]
Thanks!

```
# Build model dataset from raster stack and occ data ----
ARCAL_data <- BIOMOD_FormatingData(resp.var = thin_occ['ARCAL'],
                                   resp.xy = thin_occ[, c('long', 'lat')],
                                   expl.var = covars_nocor,
                                   resp.name = "ARCAL",
                                   PA.nb.rep = 10,
                                   PA.nb.absences = c(10000, 640),
                                   PA.strategy = 'random',
                                   filter.raster = TRUE)
```

```
! No data has been set aside for modeling evaluationError in .bm_PseudoAbsences.check.args(resp.var, expl.var, nb.rep, strategy,  : 
  You must give one value for pseudo absences, or as many as the number of repetitions
```

Seem to get this response, working on it. The thinking was to produce 10 reps of 10K for MAXNET, and 10 reps of 640 for GBM and RF (using same number of PA as presences).

**Comment by rpatin** [comment]
Sorry I did not remember the exact syntax 😕 
Then it is something like this:
`PA.nb.absences = c(rep(10000,10), rep(640, 10))`
along with 
`PA.nb.rep = 30`

**Comment by jllancaster** [comment]
No worries at all I really appreciate the help, looking at like 3000 model runs and def don't want that...thinking on what to do.

**Comment by jllancaster** [comment]
All models running now after your update this morning, thanks @rpatin

**Comment by jllancaster** [comment]
Hi @rpatin, I'm at a loss...how can I get this running without producing something around 3,000 models? I don't think it should be any more than a normal run I've been doing with PA nb.rep = 10, CV.nb.rep = 5, and three models, which produced around 180 models.

```
## Run Single Models ----
ARCAL_models <-
  BIOMOD_Modeling(
    ARCAL_data,
    modeling.id = as.character(format(Sys.time(), "%s")),
    models = c("MAXNET", "GBM", "RF"),
    bm.options = ARCAL_opt,
    models.pa = list("MAXNET" = c("PA1","PA2","PA3","PA4","PA5","PA6","PA7","PA8","PA9","PA10"), 
                     "GBM" = c("PA11","PA12","PA13","PA14","PA15","PA16","PA17","PA18","PA19","PA20"),
                     "RF" = c("PA11","PA12","PA13","PA14","PA15","PA16","PA17","PA18","PA19","PA20")),
    CV.strategy = "random",
    CV.nb.rep = 5,
    CV.perc = 0.70,
    metric.eval = c("ROC", "TSS"),
    nb.cpu = 1,
    var.import = 3,
    seed.val = 702
  )
```

**Comment by jllancaster** [comment]
Hello, to add some context to my last comment, when using models.pa as above, it looks like the estimate of the number of models to be built is somehow being multiplied by the value of PA.nb.rep. In the case of PA.nb.rep = 20, the message indicated 3000(!) models would be built, but only 150 (150*20 = 3000) models were produced as expected. Also, it appears that when running BIOMOD_Modeling with the parallel package and the above code, the number of R processes increases signficantly above the number of cores set in the parallel package, again potentially being multiplied by the number of reps. I haven't been able to document this yet.

**Comment by rpatin** [comment]
Hello @jllancaster,
Thank you for noticing, there is indeed an error in the calculation of the number of models (and number of evaluation repetitions) following the update on cross-validation and pseudo-absences. I pushed a fix in the development version (future 4.2-5) that should be ready in late august :crossed_fingers: 
Best,
Rémi

**Comment by jllancaster** [comment]
Awesome, thanks @rpatin
